# Cargar y explorar el dataset

In [7]:
import pandas as pd
data_estudiantes = pd.read_csv("Student_performance_data _.csv")
data_estudiantes.head(10)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
5,1006,18,0,0,1,8.191219,0,0,1,1,0,0,0,3.084184,1.0
6,1007,15,0,1,1,15.601680,10,0,3,0,1,0,0,2.748237,2.0
7,1008,15,1,1,4,15.424496,22,1,1,1,0,0,0,1.360143,4.0
8,1009,17,0,0,0,4.562008,1,0,2,0,1,0,1,2.896819,2.0
9,1010,16,1,0,1,18.444466,0,0,3,1,0,0,0,3.573474,0.0

In [2]:
data_estudiantes.info() #para ver las columnas y filas hay

<class 'pandas.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

In [3]:
data_estudiantes.describe() # para obtener estadísticas descriptivas de las columnas numéricas del DataFrame

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000
mean,2196.500000,16.468645,0.510870,0.877508,1.746237,9.771992,14.541388,0.301421,2.122074,0.383361,0.303512,0.196906,0.157191,1.906186,2.983696
std,690.655244,1.123798,0.499986,1.028476,1.000411,5.652774,8.467417,0.458971,1.122813,0.486307,0.459870,0.397744,0.364057,0.915156,1.233908
min,1001.000000,15.000000,0.000000,0.000000,0.000000,0.001057,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1598.750000,15.000000,0.000000,0.000000,1.000000,5.043079,7.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.174803,2.000000
50%,2196.500000,16.000000,1.000000,0.000000,2.000000,9.705363,15.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.893393,4.000000
75%,2794.250000,17.000000,1.000000,2.000000,2.000000,14.408410,22.000000,1.000000,3.000000,1.000000,1.000000,0.000000,0.000000,2.622216,4.000000
max,3392.000000,18.000000,1.000000,3.000000,4.000000,19.978094,29.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,4.000000,4.000000

# Limpieza de datos

In [4]:
data_estudiantes.isnull().sum() # para verificar si hay valores nulos en el DataFrame

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [6]:
data_estudiantes.drop_duplicates(inplace=True) # para eliminar filas duplicadas en el DataFrame, so es que hay alguna

In [15]:
data_estudiantes_COPY = data_estudiantes.copy()
data_estudiantes_COPY['Gender'] = data_estudiantes["Gender"].map({0: "Male", 1: "Female"}) #para convertir los numeros en generos y asi trabajar mas facilmente con ellos
data_estudiantes_COPY['Sports'] = data_estudiantes["Sports"].map({0: "No", 1: "Yes"})
data_estudiantes_COPY['Music'] = data_estudiantes["Music"].map({0: "No", 1: "Yes"}) 


data_estudiantes_COPY.head(10)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,Female,0,2,19.833723,7,1,2,0,No,Yes,0,2.929196,2.0
1,1002,18,Male,0,1,15.408756,0,0,1,0,No,No,0,3.042915,1.0
2,1003,15,Male,2,3,4.210570,26,0,2,0,No,No,0,0.112602,4.0
3,1004,17,Female,0,3,10.028829,14,0,3,1,No,No,0,2.054218,3.0
4,1005,17,Female,0,2,4.672495,17,1,3,0,No,No,0,1.288061,4.0
5,1006,18,Male,0,1,8.191219,0,0,1,1,No,No,0,3.084184,1.0
6,1007,15,Male,1,1,15.601680,10,0,3,0,Yes,No,0,2.748237,2.0
7,1008,15,Female,1,4,15.424496,22,1,1,1,No,No,0,1.360143,4.0
8,1009,17,Male,0,0,4.562008,1,0,2,0,Yes,No,1,2.896819,2.0
9,1010,16,Female,0,1,18.444466,0,0,3,1,No,No,0,3.573474,0.0

# Filtros

In [26]:
# mirar si las horas de estudio semanal afectan el rendimiento academico, para esto se puede hacer un filtro y luego sacar la media de cada grupo
estudiantes_con_estudio_largo = data_estudiantes_COPY[data_estudiantes_COPY["StudyTimeWeekly"] > 10]
estudiantes_con_estudio_largo["GPA"].mean() # para sacar la media de las notas finales de los estudiantes con estudio largo
print(estudiantes_con_estudio_largo["GPA"].mean())
#aca el promedio de los que estudian mas de 10h a la semana es de 2.0

2.048584874333215

In [27]:
estudiantes_con_estudio_corto = data_estudiantes_COPY[data_estudiantes_COPY["StudyTimeWeekly"] < 10]
estudiantes_con_estudio_corto["GPA"].mean() # para sacar la media de las notas finales de los estudiantes con estudio corto
print(estudiantes_con_estudio_corto["GPA"].mean())
#aca el promedio de los que estudian menos de 10h a la semana es de 1,7

1.7734496697426134

 No hay casi diferencia entre ambos pero los que estudian mas tienden a tener un poco mas de nota

In [30]:
#mirar si las actividades extracurriculares y deportes o musica afectan el rendimiento academico
estudiantes_con_deportes_o_musica = data_estudiantes_COPY[
	(data_estudiantes_COPY["Sports"] == "Yes") |
	(data_estudiantes_COPY["Music"] == "Yes")
]
estudiantes_con_deportes_o_musica["GPA"].mean() # para sacar la media de las notas finales de los estudiantes que hacen deportes o música
print(estudiantes_con_deportes_o_musica["GPA"].mean())

2.0002627448801635

In [31]:
estudiantes_sin_deportes_ni_musica = data_estudiantes_COPY[
	(data_estudiantes_COPY["Sports"] == "No") &
	(data_estudiantes_COPY["Music"] == "No")
]
estudiantes_sin_deportes_ni_musica["GPA"].mean() # para sacar la media de las notas finales de los estudiantes que no hacen deportes ni música
print(estudiantes_sin_deportes_ni_musica["GPA"].mean())

1.8309393064817696

In [32]:
#ver como afecta la absences a clase al rendimiento academico
estudiantes_con_absences_bajas = data_estudiantes_COPY[data_estudiantes_COPY["ClassAttendance"] < 15] # <15 por que es la mitad del maximo de absences que es 29
estudiantes_con_absences_bajas["GPA"].mean() # para sacar la media de las notas finales de los estudiantes con absences bajas
print(estudiantes_con_absences_bajas["GPA"].mean())

KeyError: 'ClassAttendance'

Mi hipotesis a partir de lo visto es la siguiente:

Los estudiantes que tienden a ser estudiar mas tienen mejores notas

Los estudiantes que realizan alguna actividad recreativa tienden a tener mejores notas

Por lo que digo que hay que fomentar en este caso el dedicarse mas al estudio para que se quede mejor grabado los aprendizajes y las actividades recreativas ya que ayudan a que la mente descanse adecuadamente y pueda dar lo mejor de si al momente de estudiar